name: Build and Deploy .NET 8 App to Azure WebApp (Windows) Feature

on:

  push:

    branches: [ "TeamsBot-SoftwareSuites" ]   # deploy only when main is updated

  workflow_dispatch:       # allow manual trigger

jobs:

  build-and-deploy:

    runs-on: windows-latest

    steps:

      # 1. Checkout code

      - name: Checkout

        uses: actions/checkout@v4

      # 2. Setup .NET 8

      - name: Setup .NET 8

        uses: actions/setup-dotnet@v4

        with:

          dotnet-version: '8.0.x'

      # 3. Restore

      - name: Restore dependencies

        run: dotnet restore

      # 4. Build

      - name: Build

        run: dotnet build --configuration Release --no-restore

      # 5. Publish

      - name: Publish

        run: dotnet publish -c Release -o ./publish

      # 6. Deploy to Azure WebApp

      - name: Deploy to Azure WebApp

        uses: azure/webapps-deploy@v3

        with:

          app-name: "Aries-TeamsBot"  # replace with your Web App name

          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

          package: ./publish
 